apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vprofile-ingress
  namespace: vprofile
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: add2d85891e0747068c965b45e94d103-12c18388362b3178.elb.us-east-1.amazonaws.com
    http:
      paths:
      - path: /vprofile
        pathType: Prefix
        backend:
          service:
            name: vprofile-service
            port:
              number: 80
