apiVersion: v1
kind: Service
metadata:
  name: vprofile-service
  namespace: vprofile
spec:
  type: LoadBalancer
  selector:
    app: vprofile
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
