name: EKS Deployment Workflow

on:
    push:
        branches: ["github-actions"]

jobs:
    deploy:
        name: Deploy to Amazon EKS
        runs-on: [self-hosted, label-aws2]

        env:
            EKS_CLUSTER_NAME: my_cluster
            ECR_REPOSITORY: vprofile
            IMAGE_TAG: latest

        steps:
        - name: Checkoud code
          uses: actions/checkout@v4

        - name: Set up JDK 17
          uses: actions/setup-java@v4
          with:
            java-version: '17'
            distribution: 'temurin'
            cache: maven

        - name: Build with Maven
          run: mvn -B package --file pom.xml

        - name: Run tests with Maven
          env:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          run: |
            mvn verify sonar:sonar \
                -Dsonar.projectKey=vprofile \
                -Dsonar.host.url=http://13.234.114.111:9000 \
                -Dsonar.login=$SONAR_TOKEN

        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_REGION }}

        - name: Login to Amazon ECR
          id: login-ecr
          uses: aws-actions/amazon-ecr-login@v2

        - name: Build and Tag Docker Image
          run: |
            docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
            docker tag $ECR_REPOSITORY:$IMAGE_TAG ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:$IMAGE_TAG

        - name: Insatll Trivy
          run: |
            curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh
            sudo mv ./bin/trivy /usr/local/bin/
        
        - name: Trivy Image Scan
          run: |
            IMAGE=${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:$IMAGE_TAG
            trivy image --exit-code 1 --severity CRITICAL,HIGH --format table $IMAGE

        - name: Trivy JSON Report
          run: |
            IMAGE=${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:$IMAGE_TAG
            trivy image --severity CRITICAL,HIGH --format json -o trivy-report.json $IMAGE

        - name: Upload Trivy JSON Report
          uses: actions/upload-artifact@v4
          with:
            name: trivy-report
            path: trivy-report.json

        - name: Push Docker Image to ECR
          run: |
            docker push ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:$IMAGE_TAG

        - name: Output Image URL
          run: echo "Pushed to ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:$IMAGE_TAG"

        - name: Setup Kubectl
          uses: azure/setup-kubectl@v3
          with:
            version: 'latest'

        - name: Configure kubectl for EKS
          run: |
            aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name $EKS_CLUSTER_NAME

        - name: Verify Cluaster Connection
          run: kubectl get nodes

        - name: Apply Kubernetes Deployment
          run: |
            kubectl apply -f k8s/
